framework:
  - terraform

skip-check:
  - CKV_AWS_144  # S3 cross-region replication not required for single region
  - CKV_AWS_79   # EC2 metadata service v1 - no EC2 instances in base setup
  - CKV_AWS_8    # Launch configuration public IP - not using launch configs
  - CKV_AWS_46   # EC2 detailed monitoring - minimal instances for compliance only
  - CKV_AWS_126  # EC2 detailed monitoring - minimal instances for compliance only
  - CKV_AWS_135  # EC2 EBS optimization - minimal instances for compliance only
  - CKV2_AWS_41  # EC2 IAM instance profile - minimal instances for compliance only

output: sarif
output-file-path: checkov-results.sarif
quiet: true
compact: true
