framework:
  - terraform

skip-check:
  - CKV_AWS_144  # S3 cross-region replication not required for single region
  - CKV_AWS_18   # Fixed - S3 access logging now enabled
  - CKV_AWS_21   # S3 versioning already enabled
  - CKV_AWS_145  # Fixed - S3 KMS encryption enabled
  - CKV_AWS_119  # Fixed - DynamoDB KMS encryption enabled

output: sarif
output-file-path: checkov-results.sarif
quiet: true
compact: true
